### ISSUE TITLE
Setcolor issues

### ISSUE THREAD

**Issue by coopooc** [vkiisler/JasonCoon-Fastled-WebServer#2]
First of all, thank you for writing this handler. I've been wanting something like his for a long time and really didn't want to have to move away from Fastled to get it. 

I've run into a little issue using Smartthings routines and any Alexa voice commands that deal with color. It seems that the setcolor command is being used but the handler doesn't know what to do with it. I've read a little bit here: https://community.smartthings.com/t/color-is-returned-as-a-string-when-using-latestvalue-how-to-pull-back-out-as-map/110831/3

Unfortunately, I don't know how to incorporate this into your handler. Has anyone else encountered these issues?

**Comment by vkiisler** [comment]
Converted to HSV
